"""Barchart ^EURUSD quote page as an intel source.

Public page: https://www.barchart.com/forex/quotes/%5EEURUSD

The desk reads the pair last, daily range, Barchart technical opinion,
daily pivot supports (the levels FXStreet does not list), 52-week
Fibonacci, COT crowding, and related DXY / euro-futures prints. That
snapshot feeds price integrity and the living playbook. It is context —
not an order book. Direct HTTP often hits CloudFront / a 202 challenge;
parse still works on saved HTML/markdown, and a blocked fetch never
stops the intel cycle.
"""

from __future__ import annotations

import html as html_lib
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any

import requests
from loguru import logger

from src.utils import utcnow

PAGE_URL = "https://www.barchart.com/forex/quotes/%5EEURUSD"
SOURCE = "Barchart ^EURUSD"

_UA = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 ForexSentinel/2.9"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

COT_NAMES = (
    "Commercials",
    "Non-Commercials",
    "Dealers / Intermediary",
    "Asset / Manager",
    "Leveraged Funds",
    "Other Reportables",
)


def _to_float(raw: str | None) -> float | None:
    if raw is None:
        return None
    text = str(raw).strip().replace(",", "").replace("%", "").replace("$", "").rstrip(".")
    text = text.replace("\\", "")
    if not text or text in {"n/a", "NA", "N/A", "—", "-"}:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def _to_int(raw: str | None) -> int | None:
    if raw is None:
        return None
    text = str(raw).strip().replace(",", "").replace("\\", "")
    if not text:
        return None
    try:
        return int(float(text))
    except ValueError:
        return None


def _plain(blob: str) -> str:
    text = re.sub(r"(?is)<script[^>]*>.*?</script>", " ", blob)
    text = re.sub(r"(?is)<style[^>]*>.*?</style>", " ", text)
    text = re.sub(r"(?s)<[^>]+>", " ", text)
    text = html_lib.unescape(text)
    text = text.replace("\\-", "-").replace("\\+", "+")
    text = text.replace("**", "").replace("__", "")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _is_challenge(html: str) -> bool:
    blob = (html or "").lower()
    return any(
        token in blob
        for token in (
            "just a moment",
            "cf-chl",
            "challenge-platform",
            "enable javascript and cookies to continue",
            "generated by cloudfront",
            "request blocked",
            "access denied",
            "akamai",
            "bot detection",
            "checking your browser",
        )
    )


@dataclass(slots=True)
class BCCot:
    name: str
    long: int | None
    short: int | None

    def as_dict(self) -> dict[str, Any]:
        return {**asdict(self), "net": self.net()}

    def net(self) -> int | None:
        if self.long is None or self.short is None:
            return None
        return self.long - self.short


@dataclass(slots=True)
class BCNews:
    title: str
    url: str = ""
    body: str = ""

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BCSnapshot:
    last: float | None = None
    change: float | None = None
    daily_pct: float | None = None
    bid: float | None = None
    ask: float | None = None
    day_low: float | None = None
    day_high: float | None = None
    open: float | None = None
    prev_close: float | None = None
    ytd_high: float | None = None
    ytd_low: float | None = None
    high_52w: float | None = None
    low_52w: float | None = None
    high_52w_pct: float | None = None
    weighted_alpha: float | None = None
    relative_strength: float | None = None
    five_day_pct: float | None = None
    opinion: str = ""
    opinion_pct: float | None = None
    opinion_side: str = ""
    opinion_outlook: str = ""
    r1: float | None = None
    r2: float | None = None
    r3: float | None = None
    s1: float | None = None
    s2: float | None = None
    s3: float | None = None
    fib_618: float | None = None
    fib_50: float | None = None
    fib_382: float | None = None
    perf_1m: float | None = None
    perf_3m: float | None = None
    perf_52w: float | None = None
    cot: list[BCCot] = field(default_factory=list)
    cot_as_of: str = ""
    dxy: float | None = None
    fxe: float | None = None
    euro_fx_fut: float | None = None
    news: list[BCNews] = field(default_factory=list)
    url: str = PAGE_URL
    fetched_at: datetime | None = None
    errors: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "last": self.last,
            "change": self.change,
            "daily_pct": self.daily_pct,
            "bid": self.bid,
            "ask": self.ask,
            "day_low": self.day_low,
            "day_high": self.day_high,
            "open": self.open,
            "prev_close": self.prev_close,
            "ytd_high": self.ytd_high,
            "ytd_low": self.ytd_low,
            "high_52w": self.high_52w,
            "low_52w": self.low_52w,
            "high_52w_pct": self.high_52w_pct,
            "weighted_alpha": self.weighted_alpha,
            "relative_strength": self.relative_strength,
            "five_day_pct": self.five_day_pct,
            "opinion": self.opinion,
            "opinion_pct": self.opinion_pct,
            "opinion_side": self.opinion_side,
            "opinion_outlook": self.opinion_outlook,
            "r1": self.r1,
            "r2": self.r2,
            "r3": self.r3,
            "s1": self.s1,
            "s2": self.s2,
            "s3": self.s3,
            "fib_618": self.fib_618,
            "fib_50": self.fib_50,
            "fib_382": self.fib_382,
            "perf_1m": self.perf_1m,
            "perf_3m": self.perf_3m,
            "perf_52w": self.perf_52w,
            "cot": [item.as_dict() for item in self.cot],
            "cot_as_of": self.cot_as_of,
            "dxy": self.dxy,
            "fxe": self.fxe,
            "euro_fx_fut": self.euro_fx_fut,
            "news": [item.as_dict() for item in self.news],
            "url": self.url,
            "fetched_at": self.fetched_at.isoformat() if self.fetched_at else None,
            "errors": list(self.errors),
            "source": SOURCE,
        }

    def cot_named(self, name: str) -> BCCot | None:
        needle = name.lower()
        return next((item for item in self.cot if needle in item.name.lower()), None)

    def specs_net(self) -> int | None:
        specs = self.cot_named("Non-Commercials")
        return specs.net() if specs is not None else None

    def near_day_low(self, pips: float = 15.0) -> bool:
        if self.last is None or self.day_low is None:
            return False
        return (self.last - self.day_low) <= (pips / 10_000.0)

    def driver_lines(self) -> list[str]:
        lines: list[str] = []
        if self.last is not None:
            chg = f", day {self.daily_pct:+.2f}%" if self.daily_pct is not None else ""
            rng = ""
            if self.day_low is not None and self.day_high is not None:
                rng = f"  range `{self.day_low:.5f}`–`{self.day_high:.5f}`"
            lines.append(f"Barchart ^EURUSD last `{self.last:.5f}`{chg}{rng} ({PAGE_URL}).")
        if self.opinion:
            pct = f" {self.opinion_pct:.0f}% {self.opinion_side}" if self.opinion_pct is not None else ""
            lines.append(
                f"Barchart technical opinion is **{self.opinion}**{pct}. "
                "That is not a ticket to short an RSI-oversold washout at the day low."
            )
        if self.s1 is not None:
            r1 = f", R1 `{self.r1:.5f}`" if self.r1 is not None else ""
            lines.append(
                f"Barchart daily S1 `{self.s1:.5f}` is the first real support FXStreet does not list{r1}. "
                "Fade rips into R1; do not buy a break of the day's high."
            )
        specs = self.specs_net()
        if specs is not None and specs < 0:
            lev = self.cot_named("Leveraged Funds")
            lev_bit = ""
            if lev is not None and lev.net() is not None and lev.net() < 0:
                lev_bit = f" Leveraged funds also net short {abs(lev.net()):,}."
            lines.append(
                f"Barchart COT specs are net short {abs(specs):,} contracts.{lev_bit} "
                "Do not pile into a crowded short."
            )
        elif specs is not None and specs > 0:
            lines.append(f"Barchart COT specs are net long {specs:,} contracts.")
        if self.high_52w is not None and self.low_52w is not None:
            off = ""
            if self.high_52w_pct is not None:
                off = f" Spot is {self.high_52w_pct:.2f}% off the high."
            elif self.last is not None:
                off = f" Spot is {100.0 * (self.last - self.high_52w) / self.high_52w:+.2f}% vs the high."
            fib = f" 38.2% fib `{self.fib_382:.5f}`." if self.fib_382 is not None else ""
            lines.append(
                f"Barchart 52-week range `{self.low_52w:.5f}`–`{self.high_52w:.5f}`.{off} "
                f"Spot sits below all 52w fibs.{fib}"
            )
        bits = []
        if self.five_day_pct is not None:
            bits.append(f"5-day {self.five_day_pct:+.2f}%")
        if self.perf_1m is not None:
            bits.append(f"1M {self.perf_1m:+.2f}%")
        if self.perf_52w is not None:
            bits.append(f"52w {self.perf_52w:+.2f}%")
        if self.relative_strength is not None:
            bits.append(f"RS `{self.relative_strength:.2f}`")
        if bits:
            lines.append("Barchart performance: " + ", ".join(bits) + ".")
        related = []
        if self.dxy is not None:
            related.append(f"DXY `{self.dxy:.2f}`")
        if self.fxe is not None:
            related.append(f"FXE `{self.fxe:.2f}`")
        if self.euro_fx_fut is not None:
            related.append(f"E6 `{self.euro_fx_fut:.5f}`")
        if related:
            lines.append("Barchart related: " + ", ".join(related) + ".")
        if self.news:
            lead = self.news[0]
            lines.append(f"Barchart: {lead.title}" + (f" — {lead.body[:180]}" if lead.body else ""))
        return lines[:8]


def parse_snapshot(html: str, *, now: datetime | None = None, url: str = PAGE_URL) -> BCSnapshot:
    """Pull last, opinion, pivots, COT, and performance from the ^EURUSD page."""
    snap = BCSnapshot(url=url, fetched_at=now or utcnow())
    if _is_challenge(html):
        snap.errors.append("Barchart returned a CloudFront/bot challenge. Live fetch skipped this cycle.")
        return snap
    if not html or len(html) < 200:
        snap.errors.append("Barchart page was empty.")
        return snap

    text = _plain(html)
    _parse_quote(snap, text, html)
    _parse_opinion(snap, text)
    _parse_pivots(snap, text)
    _parse_fibs(snap, text)
    _parse_performance(snap, text)
    _parse_cot(snap, text)
    _parse_related(snap, text)
    _parse_news(snap, text, html)
    if snap.last is None:
        snap.errors.append("Could not read a Barchart ^EURUSD last.")
    return snap


def _label_float(text: str, label: str) -> float | None:
    match = re.search(
        rf"{re.escape(label)}\s*[|]?\s*([+-]?\d+(?:\.\d+)?)",
        text,
        flags=re.I,
    )
    return _to_float(match.group(1) if match else None)


def _parse_quote(snap: BCSnapshot, text: str, html: str) -> None:
    header = re.search(
        r"(?:\^EURUSD|Euro/U\.S\. Dollar).{0,120}?(1\.\d{4,6})\s+([+-][\d.]+)\s+\(([+-]?[\d.]+)%\)",
        text,
        flags=re.I | re.S,
    )
    if header:
        snap.last = _to_float(header.group(1))
        snap.change = _to_float(header.group(2))
        snap.daily_pct = _to_float(header.group(3))
    if snap.last is None:
        json_last = re.search(r'"lastPrice"\s*:\s*(1\.\d+)', html)
        snap.last = _to_float(json_last.group(1) if json_last else None)
    ba = re.search(r"(1\.\d{4,6})\s+x\s+\S+\s+(1\.\d{4,6})\s+x\s+\S+", text)
    if ba:
        snap.bid = _to_float(ba.group(1))
        snap.ask = _to_float(ba.group(2))
    snap.day_low = _label_float(text, "Day Low")
    snap.day_high = _label_float(text, "Day High")
    snap.open = _label_float(text, "Open")
    snap.prev_close = _label_float(text, "Previous Close")
    snap.ytd_high = _label_float(text, "YTD High")
    snap.ytd_low = _label_float(text, "YTD Low")
    hi = re.search(r"52-Week High\s+(1\.\d{4,6})(?:\s+\(([+-]?[\d.]+)%\))?", text, flags=re.I)
    if hi:
        snap.high_52w = _to_float(hi.group(1))
        if hi.lastindex and hi.lastindex >= 2:
            snap.high_52w_pct = _to_float(hi.group(2))
    lo = re.search(r"52-Week Low\s+(1\.\d{4,6})", text, flags=re.I)
    if lo:
        snap.low_52w = _to_float(lo.group(1))
    snap.weighted_alpha = _label_float(text, "Weighted Alpha")
    rs = re.search(r"Relative Strength\s+([\d.]+)", text, flags=re.I)
    snap.relative_strength = _to_float(rs.group(1) if rs else None)
    five = re.search(r"5-Day Change[^\n]{0,40}?\(([+-]?[\d.]+)%\)", text, flags=re.I)
    snap.five_day_pct = _to_float(five.group(1) if five else None)


def _parse_opinion(snap: BCSnapshot, text: str) -> None:
    rating = re.search(
        r"Technical Opinion rating is a\s+(\d+)%\s+(Sell|Buy)",
        text,
        flags=re.I,
    )
    if rating:
        snap.opinion_pct = _to_float(rating.group(1))
        snap.opinion_side = rating.group(2).title()
    headline = re.search(
        r"(Strong sell|Strong buy|Weak sell|Weak buy|Hold|Sell|Buy)\b",
        text[max(0, text.lower().find("technical opinion")) :][:800] if "technical opinion" in text.lower() else "",
        flags=re.I,
    )
    if headline:
        snap.opinion = headline.group(1).strip().title()
    elif snap.opinion_pct is not None and snap.opinion_side:
        strength = "Strong " if (snap.opinion_pct or 0) >= 64 else ""
        snap.opinion = f"{strength}{snap.opinion_side}".strip()
    outlook = re.search(
        r"(Average|Weak|Strong)\s+short term outlook on maintaining the current direction",
        text,
        flags=re.I,
    )
    if outlook:
        snap.opinion_outlook = outlook.group(1).title() + " short-term, maintain direction"


def _parse_pivots(snap: BCSnapshot, text: str) -> None:
    snap.r3 = _label_float(text, "3rd Resistance Point")
    snap.r2 = _label_float(text, "2nd Resistance Point")
    snap.r1 = _label_float(text, "1st Resistance Point")
    snap.s1 = _label_float(text, "1st Support Level")
    snap.s2 = _label_float(text, "2nd Support Level")
    snap.s3 = _label_float(text, "3rd Support Level")


def _parse_fibs(snap: BCSnapshot, text: str) -> None:
    snap.fib_618 = _label_float(text, "Fibonacci 61.8%")
    snap.fib_50 = _label_float(text, "Fibonacci 50%")
    snap.fib_382 = _label_float(text, "Fibonacci 38.2%")


def _parse_performance(snap: BCSnapshot, text: str) -> None:
    for attr, label in (("perf_1m", "1-Month"), ("perf_3m", "3-Month"), ("perf_52w", "52-Week")):
        match = re.search(
            rf"{label}.{{0,320}}?\(([+-]?\d+\.\d+)%\)\s*since",
            text,
            flags=re.I | re.S,
        )
        setattr(snap, attr, _to_float(match.group(1) if match else None))


def _parse_cot(snap: BCSnapshot, text: str) -> None:
    as_of = re.search(r"Commitment of Traders Positions as of\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})", text, flags=re.I)
    snap.cot_as_of = as_of.group(1) if as_of else ""
    for name in COT_NAMES:
        pattern = re.escape(name) + r"\s*-\s*Long\s*/\s*Short\s+([\d,]+)\s*\([^)]+\)\s+([\d,]+)"
        match = re.search(pattern, text, flags=re.I)
        if not match:
            continue
        snap.cot.append(BCCot(name=name, long=_to_int(match.group(1)), short=_to_int(match.group(2))))


def _parse_related(snap: BCSnapshot, text: str) -> None:
    dxy = re.search(r"\$DXY.{0,80}?(\d{2,3}\.\d{2})", text, flags=re.S)
    snap.dxy = _to_float(dxy.group(1) if dxy else None)
    fxe = re.search(r"\bFXE\b.{0,80}?(\d{2,3}\.\d{2})", text, flags=re.S)
    snap.fxe = _to_float(fxe.group(1) if fxe else None)
    e6 = re.search(r"\bE6[A-Z]\d{2}\b.{0,80}?(1\.\d{3,5})", text, flags=re.S)
    snap.euro_fx_fut = _to_float(e6.group(1) if e6 else None)


def _parse_news(snap: BCSnapshot, text: str, html: str) -> None:
    title = None
    href = ""
    md = re.search(
        r"Market News and Commentary\s*\[([^\]]{12,160})\]\((https?://[^)]+)\)",
        html,
        flags=re.I | re.S,
    )
    if md:
        title = md.group(1).strip()
        href = md.group(2).strip()
    if not title:
        heading = re.search(
            r"Market News and Commentary\s+(.{12,160}?)(?:\n|Barchart\s+-)",
            text,
            flags=re.I | re.S,
        )
        if heading:
            title = re.sub(r"\s+", " ", heading.group(1)).strip()
    if not title:
        return
    body = ""
    after = text.lower().find(title.lower())
    if after >= 0:
        chunk = text[after + len(title) : after + len(title) + 700]
        chunk = re.sub(r"^[\s\-–]+", "", chunk)
        chunk = re.sub(r"\s+", " ", chunk).strip()
        body = chunk[:420]
    snap.news.append(BCNews(title=title, url=href, body=body))


def fetch_page(timeout: float = 20.0) -> str:
    response = requests.get(PAGE_URL, headers=_UA, timeout=timeout)
    if response.status_code in {202, 403, 429, 503}:
        raise RuntimeError(f"Barchart blocked ({response.status_code})")
    response.raise_for_status()
    return response.text


def fetch_eurusd_snapshot(*, timeout: float = 20.0, now: datetime | None = None) -> BCSnapshot:
    try:
        html = fetch_page(timeout=timeout)
    except Exception as exc:  # noqa: BLE001
        logger.warning("Barchart ^EURUSD fetch failed: {}", exc)
        return BCSnapshot(fetched_at=now or utcnow(), errors=[f"Barchart fetch failed: {exc}"])
    try:
        return parse_snapshot(html, now=now)
    except Exception as exc:  # noqa: BLE001
        logger.warning("Barchart ^EURUSD parse failed: {}", exc)
        return BCSnapshot(fetched_at=now or utcnow(), errors=[f"Barchart parse failed: {exc}"])
